version: "3.8"
services:
  notebook:
    container_name: mecab-notebook
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./work:/work
    working_dir: /work
    ports:
      - 8888:8888
    tty: true
    command: jupyter lab --allow-root --ip=0.0.0.0
